services:
  - type: web
    name: mastodon-bot
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: MASTODON_ACCESS_TOKEN
        value: "wnh4EFTzLOIWPG5tTRGU_JMgyqnvMr7I8khEM1pdLag"
      - key: MASTODON_API_BASE_URL
        value: "https://mastodon.social"
